### 업체 등록
POST http://localhost:8080/store
Content-Type: application/json

{
  "email" : "test@test.com",
  "open" : "10:00",
  "close" :"18:00",
  "name" : "test",
  "tel" : "02-000-0000",
  "city" : "서울",
  "street" : "강남대로",
  "zipcode" : "00000",
  "category1" : true,
  "category2" : false,
  "category3" : true,
  "category4" : false,
  "category5" : true

}